// <auto-generated />
using FirstProjectWithCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstProjectWithCore.Migrations
{
    [DbContext(typeof(TestDbCoreDbContext))]
    partial class TestDbCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FirstProjectWithCore.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenSv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSV");

                    b.ToTable("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
